server:
  port: 9010
eureka:
  client:
    service-url:
      defaultZone: http://dpb:123456@eureka1:8761/eureka/
spring:
  application:
    name: e-book-consumer-zipkin
  zipkin:
    base-url: http://localhost:9411



