spring:
  application:
    name: config-server
  profiles:
    active: rabbitmq
  #Git配置
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/dengpbs/config

server:
  port: 9050

#设置服务注册中心地址，指向另一个注册中心
eureka:
  client:
    service-url:
      defaultZone: http://dpb:123456@eureka1:8761/eureka/

management:
  security:
    enabled: false