server:
  port: 9030

spring:
  application:
    name: zuul-gateway-filter-zipkin
  sleuth:
    sampler: 1.0
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://dpb:123456@eureka1:8761/eureka/

zuul:
  servlet-path: /
  routes:
    api-a:
      path: /custom/**
      stripPrefix: true
      serviceId: E-BOOK-CONSUMER-ZIPKIN
    api-b:
      path: /**
      stripPrefix: true
      serviceId: SLEUTH-PRODUCT-PROVIDER-ZIPKIN